"""add membership suspension reason

Revision ID: 369074c6389d
Revises: 264a8d8a0705
Create Date: 2026-09-21 13:07:38.880078
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '369074c6389d'
down_revision: Union[str, None] = '264a8d8a0705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memberships', sa.Column('suspension_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memberships', 'suspension_reason')
    # ### end Alembic commands ###
