<script setup lang="ts">
import { onMounted, ref, watch } from "vue";
import { ArrowLeft, Check, ShieldAlert, X } from "@lucide/vue";
import { api, formatDate, type AdminMembership } from "../../api";
import ConfirmDialog from "../../components/ConfirmDialog.vue";
import { notify } from "../../toast";

const props = defineProps<{ id: string }>(); const emit = defineEmits<{ navigate: [path: string] }>();
const membership = ref<AdminMembership | null>(null); const loading = ref(true); const error = ref(""); const action = ref<"approve" | "reject" | "suspend" | null>(null); const busy = ref(false); const reason = ref(""); const actionError = ref("");
async function load() { loading.value = true; error.value = ""; try { membership.value = await api<AdminMembership>(`/api/v1/admin/memberships/${props.id}`); } catch (caught) { error.value = caught instanceof Error ? caught.message : "Unable to load membership."; } finally { loading.value = false; } }
async function submitAction() { if (!action.value) return; if (action.value !== "approve" && !reason.value.trim()) { actionError.value = "A reason is required."; return; } busy.value = true; actionError.value = ""; try { membership.value = await api<AdminMembership>(`/api/v1/admin/memberships/${props.id}/${action.value}`, { method: "POST", ...(action.value === "approve" ? {} : { body: JSON.stringify({ reason: reason.value }) }) }); notify(`Membership ${action.value === 'approve' ? 'approved' : action.value === 'reject' ? 'rejected' : 'suspended'}`); action.value = null; reason.value = ""; } catch (caught) { actionError.value = caught instanceof Error ? caught.message : "Unable to update membership."; } finally { busy.value = false; } }
watch(() => props.id, load); onMounted(load);
</script>
<template>
  <main class="review-page"><button class="back-link" type="button" @click="emit('navigate', '/admin/members')"><ArrowLeft :size="17" />Members</button><div v-if="loading" class="review-loading"><span></span><span></span></div><section v-else-if="error" class="review-state"><h1>Membership unavailable</h1><p>{{ error }}</p></section><template v-else-if="membership"><header><div><p class="eyebrow">Membership review</p><h1>{{ membership.user.name }}</h1><p>{{ membership.user.email }}</p></div><em :class="membership.status.toLowerCase()">{{ membership.status }}</em></header><section class="review-layout"><div class="member-summary"><span class="member-initials">{{ membership.user.name.split(/\s+/).slice(0,2).map((part) => part[0]).join('').toUpperCase() }}</span><h2>{{ membership.user.name }}</h2><p>{{ membership.user.email }}</p></div><dl><div><dt>Status</dt><dd>{{ membership.status }}</dd></div><div><dt>Applied</dt><dd>{{ formatDate(membership.applied_at) }}</dd></div><div v-if="membership.member_number"><dt>Member number</dt><dd>{{ membership.member_number }}</dd></div><div v-if="membership.approved_at"><dt>Approved</dt><dd>{{ formatDate(membership.approved_at) }}</dd></div><div v-if="membership.expires_at"><dt>Valid until</dt><dd>{{ formatDate(membership.expires_at) }}</dd></div><div v-if="membership.rejection_reason"><dt>Rejection reason</dt><dd>{{ membership.rejection_reason }}</dd></div><div v-if="membership.suspension_reason"><dt>Suspension reason</dt><dd>{{ membership.suspension_reason }}</dd></div></dl></section><section v-if="membership.status === 'PENDING'" class="review-actions"><div><p class="eyebrow">Decision required</p><h2>Review this application.</h2><p>Approval activates membership and lets the backend generate the member number and validity period.</p></div><div><button type="button" @click="action = 'reject'; actionError = ''"><ShieldAlert :size="17" />Reject</button><button type="button" @click="action = 'approve'; actionError = ''"><Check :size="17" />Approve</button></div></section><section v-else-if="membership.status === 'ACTIVE'" class="review-actions"><div><p class="eyebrow">Membership controls</p><h2>Active membership</h2><p>Suspension immediately removes active member access and requires a reason.</p></div><div><button class="suspend-button" type="button" @click="action = 'suspend'; actionError = ''"><ShieldAlert :size="17" />Suspend membership</button></div></section></template>
    <ConfirmDialog :open="action === 'approve'" title="Approve membership?" :message="`${membership?.user.name || 'This user'} will receive active Litera membership. The backend will generate all membership details.`" confirm-label="Approve" :busy="busy" @cancel="action = null" @confirm="submitAction" />
    <Teleport to="body"><div v-if="action === 'reject' || action === 'suspend'" class="reason-backdrop" @click.self="action = null"><section class="reason-dialog" role="dialog" aria-modal="true"><header><h2>{{ action === 'reject' ? 'Reject application' : 'Suspend membership' }}</h2><button type="button" aria-label="Close" @click="action = null"><X :size="20" /></button></header><p>{{ action === 'reject' ? 'Explain why this application was not approved.' : 'Explain why this active membership is being suspended.' }}</p><label>Reason<textarea v-model="reason" rows="4" maxlength="1000"></textarea></label><p v-if="actionError" class="action-error" role="alert">{{ actionError }}</p><footer><button type="button" @click="action = null">Cancel</button><button type="button" :disabled="busy" @click="submitAction">{{ busy ? 'Working...' : action === 'reject' ? 'Reject application' : 'Suspend membership' }}</button></footer></section></div></Teleport>
  </main>
</template>
<style scoped>
.review-page { padding: 52px clamp(28px, 6vw, 90px) 110px; }.back-link { display: inline-flex; align-items: center; gap: 8px; padding: 7px 0; background: transparent; color: #69716b; }.review-page > header { display: flex; justify-content: space-between; align-items: end; gap: 30px; padding: 50px 0 55px; }.review-page h1 { margin: 0; font-size: clamp(3rem, 5vw, 5rem); font-weight: 560; }.review-page header p:not(.eyebrow) { color: #6f766f; }.review-page header em { padding: 7px 10px; background: #e2e5e2; font-size: .68rem; font-style: normal; }.review-page header em.pending { background: #f0e5c8; color: #725c28; }.review-page header em.active { background: #d8e8df; color: #315a46; }.review-page header em.rejected, .review-page header em.suspended { background: #ecdcd8; color: #82483e; }.review-layout { display: grid; grid-template-columns: .7fr 1.3fr; gap: 8vw; padding: 55px; background: #dce8e3; }.member-initials { display: grid; width: 85px; height: 85px; margin-bottom: 25px; place-items: center; border-radius: 50%; background: #173d32; color: white; font-size: 1.4rem; font-weight: 700; }.member-summary h2 { margin: 0 0 8px; font-size: 1.7rem; }.member-summary p { color: #657069; }.review-layout dl { margin: 0; border-top: 1px solid #a9bbb2; }.review-layout dl div { display: flex; justify-content: space-between; gap: 30px; padding: 17px 0; border-bottom: 1px solid #a9bbb2; }.review-layout dt { color: #67746d; font-size: .76rem; }.review-layout dd { max-width: 65%; margin: 0; overflow-wrap: anywhere; text-align: right; }.review-actions { display: grid; grid-template-columns: 1fr auto; gap: 60px; align-items: end; padding: 75px 0; border-bottom: 1px solid #cdd2cd; }.review-actions h2 { margin: 0; font-size: 2.2rem; }.review-actions p:not(.eyebrow) { max-width: 590px; color: #6c736d; line-height: 1.6; }.review-actions > div:last-child { display: flex; gap: 9px; }.review-actions button { display: flex; align-items: center; gap: 8px; min-height: 43px; padding: 0 15px; border: 1px solid #a5483c; background: transparent; color: #8b3d33; }.review-actions button:last-child { border-color: #173d32; background: #173d32; color: white; }.review-actions .suspend-button { border-color: #a5483c; background: transparent; color: #8b3d33; }.review-loading { display: grid; gap: 20px; padding-top: 60px; }.review-loading span { height: 110px; background: #e1e4e0; }.review-state { padding: 100px 0; }.review-state p { color: #6f766f; }
.reason-backdrop { position: fixed; z-index: 90; inset: 0; display: grid; padding: 20px; place-items: center; background: rgba(20,26,22,.48); }.reason-dialog { width: min(500px, 100%); padding: 32px; background: #f7f8f5; }.reason-dialog header { display: flex; justify-content: space-between; }.reason-dialog h2 { margin: 0; }.reason-dialog header button { padding: 3px; background: transparent; }.reason-dialog > p { color: #6c736d; line-height: 1.6; }.reason-dialog label { display: grid; gap: 8px; color: #555d57; font-size: .76rem; font-weight: 650; }.reason-dialog textarea { padding: 9px; border: 1px solid #b9c0ba; background: white; font: inherit; resize: vertical; }.reason-dialog footer { display: flex; justify-content: flex-end; gap: 9px; margin-top: 25px; }.reason-dialog footer button { min-height: 42px; padding: 0 15px; border: 1px solid #b4bbb5; background: transparent; }.reason-dialog footer button:last-child { border-color: #a5483c; background: #a5483c; color: white; }.action-error { color: #a14539 !important; font-size: .82rem; }
@media (max-width: 750px) { .review-page { padding: 75px 22px; }.review-page > header { display: block; }.review-page header em { display: inline-block; margin-top: 15px; }.review-layout { grid-template-columns: 1fr; padding: 35px 24px; }.review-actions { grid-template-columns: 1fr; gap: 25px; }.review-actions > div:last-child { flex-direction: column-reverse; }.review-actions button { justify-content: center; } }
</style>
