<script setup lang="ts">
import { computed, onMounted, ref, watch } from "vue";
import { Pencil, Plus, Search, Trash2, X } from "@lucide/vue";
import { api, type Author, type Category, type Page } from "../../api";
import ConfirmDialog from "../../components/ConfirmDialog.vue";
import { notify } from "../../toast";

const props = defineProps<{ kind: "categories" | "authors" }>();
type Item = Category & { bio?: string | null; photo_url?: string | null };
const items = ref<Item[]>([]); const loading = ref(true); const error = ref(""); const search = ref(""); const showForm = ref(false); const editing = ref<Item | null>(null); const saving = ref(false); const formError = ref(""); const deleting = ref<Item | null>(null); const deleteBusy = ref(false);
const form = ref({ name: "", description: "", bio: "", photo_url: "" });
const singular = computed(() => props.kind === "categories" ? "category" : "author");
const filtered = computed(() => items.value.filter((item) => item.name.toLowerCase().includes(search.value.toLowerCase())));
async function load() { loading.value = true; error.value = ""; try { const response = await api<Page<Category | Author>>(`/api/v1/${props.kind}?page_size=100`); items.value = response.items as Item[]; } catch (caught) { error.value = caught instanceof Error ? caught.message : `Unable to load ${props.kind}.`; } finally { loading.value = false; } }
function openForm(item?: Item) { editing.value = item || null; form.value = { name: item?.name || "", description: item?.description || "", bio: item?.bio || "", photo_url: item?.photo_url || "" }; formError.value = ""; showForm.value = true; }
async function save() { saving.value = true; formError.value = ""; const payload = props.kind === "categories" ? { name: form.value.name, description: form.value.description || null } : { name: form.value.name, bio: form.value.bio || null, photo_url: form.value.photo_url || null }; try { const path = editing.value ? `/api/v1/admin/${props.kind}/${editing.value.id}` : `/api/v1/admin/${props.kind}`; await api(path, { method: editing.value ? "PATCH" : "POST", body: JSON.stringify(payload) }); notify(`${singular.value[0].toUpperCase() + singular.value.slice(1)} ${editing.value ? 'updated' : 'created'}`); showForm.value = false; load(); } catch (caught) { formError.value = caught instanceof Error ? caught.message : `Unable to save ${singular.value}.`; } finally { saving.value = false; } }
async function confirmDelete() { if (!deleting.value) return; deleteBusy.value = true; try { await api(`/api/v1/admin/${props.kind}/${deleting.value.id}`, { method: "DELETE" }); notify(`${singular.value[0].toUpperCase() + singular.value.slice(1)} deleted`); deleting.value = null; load(); } catch (caught) { notify(caught instanceof Error ? caught.message : `Unable to delete ${singular.value}.`, "error"); } finally { deleteBusy.value = false; } }
watch(() => props.kind, () => { search.value = ""; load(); }); onMounted(load);
</script>
<template>
  <main class="taxonomy-page"><header><div><p class="eyebrow">Library structure</p><h1>{{ kind === 'categories' ? 'Categories' : 'Authors' }}</h1><p>{{ kind === 'categories' ? 'Organize the catalog into clear areas of interest.' : 'Manage the people behind every title.' }}</p></div><button type="button" @click="openForm()"><Plus :size="17" />Add {{ singular }}</button></header><label class="taxonomy-search"><Search :size="18" /><span class="sr-only">Search {{ kind }}</span><input v-model="search" type="search" :placeholder="`Search ${kind}`" /></label><div v-if="loading" class="taxonomy-loading"><span v-for="i in 5" :key="i"></span></div><div v-else-if="error" class="taxonomy-state"><h2>Unable to load {{ kind }}.</h2><p>{{ error }}</p></div><div v-else-if="!filtered.length" class="taxonomy-state"><h2>No {{ kind }} found.</h2><p>{{ search ? 'Try another search.' : `Add the first ${singular}.` }}</p></div><section v-else class="taxonomy-list"><div class="list-head"><span>Name</span><span>{{ kind === 'categories' ? 'Description' : 'Biography' }}</span><span></span></div><article v-for="item in filtered" :key="item.id"><div class="item-name"><span v-if="kind === 'authors'" class="author-photo"><img v-if="item.photo_url" :src="item.photo_url" alt="" />{{ item.photo_url ? '' : item.name[0] }}</span><strong>{{ item.name }}</strong></div><p>{{ (kind === 'categories' ? item.description : item.bio) || 'No description provided.' }}</p><div><button type="button" :aria-label="`Edit ${item.name}`" @click="openForm(item)"><Pencil :size="17" /></button><button type="button" :aria-label="`Delete ${item.name}`" @click="deleting = item"><Trash2 :size="17" /></button></div></article></section>
    <Teleport to="body"><div v-if="showForm" class="form-backdrop" @click.self="showForm = false"><section class="taxonomy-form" role="dialog" aria-modal="true"><header><h2>{{ editing ? 'Edit' : 'Add' }} {{ singular }}</h2><button type="button" aria-label="Close" @click="showForm = false"><X :size="20" /></button></header><form @submit.prevent="save"><label>Name<input v-model="form.name" required maxlength="255" /></label><label v-if="kind === 'categories'">Description<textarea v-model="form.description" rows="4"></textarea></label><template v-else><label>Biography<textarea v-model="form.bio" rows="4"></textarea></label><label>Photo URL <small>Optional</small><input v-model="form.photo_url" type="url" maxlength="2048" /></label></template><p v-if="formError" class="form-error">{{ formError }}</p><footer><button type="button" @click="showForm = false">Cancel</button><button type="submit" :disabled="saving">{{ saving ? 'Saving...' : 'Save' }}</button></footer></form></section></div></Teleport>
    <ConfirmDialog :open="Boolean(deleting)" :title="`Delete ${deleting?.name || singular}?`" :message="`This will only succeed if the ${singular} is not assigned to any books.`" :confirm-label="`Delete ${singular}`" destructive :busy="deleteBusy" @cancel="deleting = null" @confirm="confirmDelete" />
  </main>
</template>
<style scoped>
.taxonomy-page { padding: 58px clamp(28px, 6vw, 90px) 100px; }.taxonomy-page > header { display: flex; justify-content: space-between; align-items: end; gap: 30px; }.taxonomy-page h1 { margin: 0; font-size: clamp(3rem, 5vw, 5rem); font-weight: 560; }.taxonomy-page header p:not(.eyebrow) { color: #717872; }.taxonomy-page > header > button { display: flex; align-items: center; gap: 8px; min-height: 43px; padding: 0 16px; border-radius: 3px; background: #173d32; color: white; }.taxonomy-search { display: flex; align-items: center; gap: 10px; width: min(440px, 100%); margin: 50px 0 25px; border-bottom: 1px solid #a3aaa4; }.taxonomy-search input { width: 100%; height: 43px; border: 0; outline: 0; background: transparent; }.taxonomy-list { border-top: 1px solid #cbd0cb; }.list-head, .taxonomy-list article { display: grid; grid-template-columns: .8fr 1.5fr 75px; gap: 25px; align-items: center; padding: 17px 8px; border-bottom: 1px solid #d4d8d4; }.list-head { color: #838983; font-size: .67rem; text-transform: uppercase; }.taxonomy-list p { display: -webkit-box; margin: 0; overflow: hidden; color: #6f766f; font-size: .85rem; -webkit-box-orient: vertical; -webkit-line-clamp: 2; }.taxonomy-list article > div:last-child { display: flex; }.taxonomy-list article button { display: grid; width: 35px; height: 35px; place-items: center; background: transparent; }.item-name { display: flex; align-items: center; gap: 12px; }.author-photo { display: grid; width: 38px; height: 38px; overflow: hidden; place-items: center; border-radius: 50%; background: #dce8e3; color: #446052; }.author-photo img { width: 100%; height: 100%; object-fit: cover; }.taxonomy-state { padding: 70px 0; border-block: 1px solid #d0d5d0; }.taxonomy-state h2 { margin: 0 0 8px; }.taxonomy-state p { color: #747b75; }.taxonomy-loading { display: grid; gap: 1px; }.taxonomy-loading span { height: 68px; background: #e2e5e1; }
.form-backdrop { position: fixed; z-index: 70; inset: 0; display: grid; padding: 20px; place-items: center; background: rgba(20,26,22,.48); }.taxonomy-form { width: min(520px, 100%); padding: 30px; background: #f7f8f5; }.taxonomy-form > header { display: flex; justify-content: space-between; }.taxonomy-form h2 { margin: 0 0 25px; }.taxonomy-form header button { align-self: start; padding: 4px; background: transparent; }.taxonomy-form form, .taxonomy-form label { display: grid; gap: 18px; }.taxonomy-form label { gap: 7px; color: #555d57; font-size: .76rem; font-weight: 650; }.taxonomy-form input, .taxonomy-form textarea { width: 100%; padding: 9px; border: 1px solid #bbc2bc; background: white; font: inherit; }.taxonomy-form textarea { resize: vertical; }.taxonomy-form footer { display: flex; justify-content: flex-end; gap: 8px; }.taxonomy-form footer button { min-height: 42px; padding: 0 15px; border: 1px solid #b4bbb5; background: transparent; }.taxonomy-form footer button:last-child { background: #173d32; color: white; }.form-error { margin: 0; color: #a14539; }
@media (max-width: 650px) { .taxonomy-page { padding: 75px 22px; }.taxonomy-page > header { display: block; }.taxonomy-page > header > button { margin-top: 24px; }.list-head { display: none; }.taxonomy-list article { grid-template-columns: 1fr auto; }.taxonomy-list article > p { grid-column: 1/-1; }.taxonomy-list article > div:last-child { grid-column: 2; grid-row: 1; } }
</style>
