<script setup lang="ts">
import { computed, onMounted, ref, watch } from "vue";
import { ArrowLeft, ArrowRight, Search, UsersRound } from "@lucide/vue";
import { api, formatDate, type AdminMembership, type MembershipPage } from "../../api";

const emit = defineEmits<{ navigate: [path: string] }>();
const params = new URLSearchParams(location.search);
const status = ref(params.get("status") || ""); const search = ref(""); const page = ref(1); const data = ref<MembershipPage | null>(null); const loading = ref(true); const error = ref(""); let timer = 0;
const items = computed(() => [...(data.value?.items || [])].sort((a, b) => Number(b.status === "PENDING") - Number(a.status === "PENDING")));
async function load() { loading.value = true; error.value = ""; const query = new URLSearchParams({ page: String(page.value), page_size: "20" }); if (status.value) query.set("status", status.value); if (search.value.trim()) query.set("search", search.value.trim()); history.replaceState({}, "", `/admin/members?${query}`); try { data.value = await api<MembershipPage>(`/api/v1/admin/memberships?${query}`); } catch (caught) { error.value = caught instanceof Error ? caught.message : "Unable to load members."; } finally { loading.value = false; } }
function changePage(next: number) { page.value = next; load(); }
watch(search, () => { clearTimeout(timer); timer = window.setTimeout(() => { page.value = 1; load(); }, 350); }); onMounted(load);
</script>
<template>
  <main class="members-page"><header><p class="eyebrow">Membership</p><h1>Members</h1><p>Review applications and maintain active membership access.</p></header><section class="member-tools"><label><Search :size="18" /><span class="sr-only">Search members</span><input v-model="search" type="search" placeholder="Search name, email, or member number" /></label><select v-model="status" aria-label="Filter membership status" @change="page = 1; load()"><option value="">All statuses</option><option>PENDING</option><option>ACTIVE</option><option>REJECTED</option><option>EXPIRED</option><option>SUSPENDED</option></select></section><div v-if="loading" class="member-loading"><span v-for="i in 6" :key="i"></span></div><div v-else-if="error" class="member-state"><h2>Memberships could not be loaded.</h2><p>{{ error }}</p></div><div v-else-if="!items.length" class="member-state"><UsersRound :size="30" /><h2>No memberships found.</h2><p>There are no applications matching this view.</p></div><template v-else><section class="member-list"><div class="list-head"><span>Member</span><span>Status</span><span>Applied</span><span>Valid until</span><span></span></div><button v-for="member in items" :key="member.id" type="button" @click="emit('navigate', `/admin/members/${member.id}`)"><span class="member-name"><strong>{{ member.user.name }}</strong><small>{{ member.user.email }}</small></span><span data-label="Status"><em :class="member.status.toLowerCase()">{{ member.status }}</em></span><span data-label="Applied">{{ formatDate(member.applied_at) }}</span><span data-label="Valid until">{{ formatDate(member.expires_at) || '-' }}</span><ArrowRight :size="17" /></button></section><nav v-if="data && data.total > data.page_size" class="member-pagination"><button type="button" :disabled="page === 1" @click="changePage(page - 1)"><ArrowLeft :size="17" /></button><span>Page {{ page }}</span><button type="button" :disabled="page * data.page_size >= data.total" @click="changePage(page + 1)"><ArrowRight :size="17" /></button></nav></template>
  </main>
</template>
<style scoped>
.members-page { padding: 58px clamp(28px, 6vw, 90px) 100px; }.members-page > header h1 { margin: 0; font-size: clamp(3rem, 5vw, 5rem); font-weight: 560; }.members-page > header p:last-child { color: #707771; }.member-tools { display: flex; gap: 18px; margin: 50px 0 25px; }.member-tools label { display: flex; align-items: center; gap: 10px; width: min(460px, 100%); border-bottom: 1px solid #a1a8a2; }.member-tools input { width: 100%; height: 42px; border: 0; outline: 0; background: transparent; }.member-tools select { min-width: 170px; border: 0; border-bottom: 1px solid #a1a8a2; background: transparent; }.member-list { border-top: 1px solid #cbd0cb; }.list-head, .member-list > button { display: grid; grid-template-columns: 1.5fr .7fr .8fr .8fr 25px; gap: 20px; align-items: center; width: 100%; padding: 17px 8px; border-bottom: 1px solid #d4d8d4; background: transparent; text-align: left; }.list-head { color: #838983; font-size: .67rem; text-transform: uppercase; }.member-name { display: grid; gap: 5px; }.member-name small { color: #767d77; }.member-list em { padding: 5px 8px; background: #e2e5e2; font-size: .62rem; font-style: normal; }.member-list em.pending { background: #f0e5c8; color: #725c28; }.member-list em.active { background: #d8e8df; color: #315a46; }.member-list em.rejected, .member-list em.suspended { background: #ecdcd8; color: #82483e; }.member-state { padding: 75px 0; border-block: 1px solid #d2d6d2; }.member-state h2 { margin: 14px 0 8px; }.member-state p { color: #757c76; }.member-loading { display: grid; gap: 1px; }.member-loading span { height: 70px; background: #e2e5e1; }.member-pagination { display: flex; justify-content: flex-end; align-items: center; gap: 14px; margin-top: 30px; }.member-pagination button { display: grid; width: 38px; height: 38px; place-items: center; border: 1px solid #cbd0cb; background: transparent; }.member-pagination span { color: #747b75; font-size: .78rem; }
@media (max-width: 750px) { .members-page { padding: 75px 22px; }.member-tools { flex-direction: column; }.member-tools select { height: 42px; }.list-head { display: none; }.member-list > button { grid-template-columns: 1fr auto; gap: 9px 18px; }.member-list > button > span:not(.member-name) { grid-column: 1; }.member-list > button > span:not(.member-name)::before { margin-right: 8px; color: #888f89; content: attr(data-label) ":"; font-size: .67rem; }.member-list > button > svg { grid-column: 2; grid-row: 1; } }
</style>
